parameters:
#    neutral_page.example.class: Neutral\PageBundle\Example

services:
#    neutral_page.example:
#        class: %neutral_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
