parameters:
#    neutral_frontend.example.class: Neutral\FrontendBundle\Example

services:
#    neutral_frontend.example:
#        class: %neutral_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
