parameters:
    neutral_admin.form.type.tags.class: Neutral\AdminBundle\Form\Type\TagsType

services:
    neutral_admin.form.type.tags:
        class: %neutral_admin.form.type.tags.class%
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: tags }
