neutral_blog:
    resource: "@NeutralBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

neutral_admin:
    resource: "@NeutralAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

neutral_user:
    resource: "@NeutralUserBundle/Resources/config/routing.yml"
    prefix:   /

neutral_frontend:
    resource: "@NeutralFrontendBundle/Resources/config/routing.yml"
    prefix:   /

neutral_page:
    resource: "@NeutralPageBundle/Resources/config/routing.yml"
    prefix:   /page

