neutral_blog:
    resource: "@NeutralBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

neutral_admin:
    resource: "@NeutralAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

neutral_user:
    resource: "@NeutralUserBundle/Resources/config/routing.yml"
    prefix:   /

neutral_homepage:
    pattern:  /
    defaults:
        _controller: NeutralPageBundle:Page:view
        slug: home

neutral_page:
    resource: "@NeutralPageBundle/Resources/config/routing.yml"
    prefix:   /

