neutral_user:
    resource: "@NeutralUserBundle/Resources/config/routing.yml"
    prefix:   /

neutral_frontend:
    resource: "@NeutralFrontendBundle/Resources/config/routing.yml"
    prefix:   /

neutral_page:
    resource: "@NeutralPageBundle/Resources/config/routing.yml"
    prefix:   /page

