neutral_blog_index:
    pattern:  /
    defaults: { _controller: NeutralBlogBundle:Post:list }
    
neutral_blog_post:
    pattern:  /{slug}
    defaults: { _controller: NeutralBlogBundle:Post:post }
