Neutral\BlogBundle\Entity\Tag:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        title:
            type: string
            length: 255
        weight:
            type: integer
    uniqueConstraints:
        title_idx:
            columns: [title]
    manyToMany:
        posts:
            targetEntity: Post
            mappedBy: tags
    lifecycleCallbacks: {  }
