login:
    pattern:  /login
    defaults: { _controller: NeutralUserBundle:Security:login }

login_check:
    pattern:   /login_check
    
logout:
    pattern:   /logout
    defaults: { _controller: NeutralUserBundle:Security:logout }